-- Export Slices to Text File.lua
-- Saves all slice information (name, bounds, 9-patch, pivot) to a .txt file

local sprite = app.activeSprite
if not sprite then
    app.alert("Error: No active sprite!")
    return
end

-- Choose output file (same folder as .aseprite, named after the file)
local baseName = app.fs.fileTitle(sprite.filename)
local defaultPath = app.fs.joinPath(app.fs.filePath(sprite.filename), baseName .. "_slices.txt")

local file = io.open(defaultPath, "w")
if not file then
    app.alert("Error: Could not write to file!")
    return
end

file:write(string.format("# Sprite: %s\n", sprite.filename))
file:write(string.format("# Resolution: %dx%d\n", sprite.width, sprite.height))
-- file:write(string.format("Total Slices: %d\n", #sprite.slices))
-- file:write(string.rep("=", 60) .. "\n\n")

local index = 1
for _, slice in ipairs(sprite.slices) do
    local b = slice.bounds
    local center = slice.center
    local pivot = slice.pivot

    file:write(string.format("[%d] Name: \"%s\"\n", index, slice.name or "(no name)"))
    file:write(string.format("     Bounds: x=%d, y=%d, w=%d, h=%d\n", b.x, b.y, b.width, b.height))

    -- if center and not center.isEmpty then
    --     file:write(string.format("     9-Patch Center: x=%d, y=%d, w=%d, h=%d\n",
    --         center.x, center.y, center.width, center.height))
    -- end

    if pivot then
        file:write(string.format("     Pivot: x=%d, y=%d\n", pivot.x, pivot.y))
    end

    -- Optional: include slice data string (for custom tags)
    if slice.data and slice.data ~= "" then
        file:write(string.format("     Data: %s\n", slice.data))
    end

    file:write("\n")
    index = index + 1
end

file:write("#Generated by Aseprite - Export Slices to Text File\n")
file:close()

app.alert{
    title = "Slices Exported",
    text = string.format("Successfully saved %d slices to:\n%s", #sprite.slices, defaultPath),
    buttons = "OK"
}